### ISSUE TITLE
Deploy to Heroku does not work

### ISSUE THREAD

**Issue by jtreitz** [honeypotio/sidekiq_dashboard#1]
Item could not be created:
Unknown Error. Please contact support

**Comment by duksis** [comment]
created a support ticket for Heroku - thanks

**Comment by duksis** [comment]
Response from heroku

> Hi Hugo,
> 
> This issue was caused by platform incident [#1158](https://status.heroku.com/incidents/1158). We have now resolved the issue and your Button deploy should be working.
> 
> Cheers,
> Keith
>
